import type { PricingPlan } from "@/types/domain";

export const pricingPlans: PricingPlan[] = [
  {
    id: "free",
    name: "Free",
    tierLabel: "Trial access",
    price: "$0",
    credits: 100,
    description: "For first-time visitors who want to test the chat flow before choosing a paid membership.",
    modelAccess: "Free Chatbot",
    memory: "No persistent memory",
    features: [
      "100 starter credits",
      "Free chatbot model",
      "All public characters",
      "Enough for roughly 30-40 trial messages",
      "Upgrade anytime",
    ],
  },
  {
    id: "silver",
    name: "Silver",
    tierLabel: "Starter access",
    price: "$14",
    credits: 2500,
    description: "For casual private chats with the standard uncensored model and enough credits to explore the library.",
    modelAccess: "Standard Uncensored",
    memory: "Basic memory for 3 characters",
    features: [
      "2,500 monthly credits",
      "Standard uncensored chat model",
      "All public characters",
      "Regenerate and continue tools",
      "Basic character memory",
    ],
  },
  {
    id: "gold",
    name: "Gold",
    tierLabel: "Most popular",
    price: "$29",
    credits: 7500,
    description: "For regular users who want richer roleplay, stronger continuity, and more remembered character arcs.",
    modelAccess: "Standard + model controls",
    memory: "Advanced memory for 15 characters",
    features: [
      "7,500 monthly credits",
      "Standard uncensored chat model",
      "Advanced character memory",
      "Longer context retention",
      "Early character drops",
      "Priority support queue",
    ],
    highlighted: true,
  },
  {
    id: "platinum",
    name: "Platinum",
    tierLabel: "Ultra access",
    price: "$79",
    credits: 18000,
    description: "For premium users who want Premium AI, deeper memory, faster drops, and the highest chat experience.",
    modelAccess: "Standard + Premium AI",
    memory: "Advanced memory for 60 characters",
    badge: "Unlocks Ultra Erotik",
    features: [
      "18,000 monthly credits",
      "Premium AI model access",
      "Choose chat AI per conversation",
      "Advanced long-term memory",
      "Priority generation and new characters",
      "Image and voice roadmap access",
    ],
  },
];
