import type { Metadata } from "next";
import { LegalPage } from "@/components/layout/legal-page";
import { siteConfig } from "@/lib/config";

export const metadata: Metadata = { title: "Terms of Service" };

const SectionTitle = ({ children }: { children: React.ReactNode }) => (
  <h2 className="pt-4 text-xl font-bold text-white">{children}</h2>
);

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Service">
      <p className="text-xs text-zinc-500">Last updated: June 12, 2026</p>

      <SectionTitle>1. The Service</SectionTitle>
      <p>
        {siteConfig.name} (&quot;the Service&quot;) is an entertainment platform that provides fictional,
        AI-generated chat conversations with virtual characters, including adult-oriented and erotic
        content. All characters are entirely synthetic. They are not real people, they do not depict
        real people, and every character is presented as an adult aged 18 or older.
      </p>

      <SectionTitle>2. Eligibility (18+)</SectionTitle>
      <p>
        You must be at least 18 years old — or the age of majority in your jurisdiction, whichever is
        higher — to access the Service. By creating an account or using the Service you represent and
        warrant that you meet this requirement and that accessing adult content is legal where you
        live. We may suspend or terminate accounts we reasonably believe belong to minors.
      </p>

      <SectionTitle>3. Acceptable Use</SectionTitle>
      <p>
        The Service may only be used for lawful, fictional, consensual adult entertainment. You agree
        not to use the Service to request, generate, or share content involving: minors or characters
        presented as minors in any sexual context; non-consensual sexual activity; depictions of real,
        identifiable people without their consent; incitement of violence or illegal acts; or any
        content that violates applicable law. Violations result in immediate account termination and,
        where legally required, reporting to the relevant authorities. See our{" "}
        <a href="/content-policy" className="text-fuchsia-400 hover:text-fuchsia-300">Content Policy</a> for details.
      </p>

      <SectionTitle>4. Accounts, Credits and Subscriptions</SectionTitle>
      <p>
        Conversations consume credits granted by your subscription tier. Subscriptions renew
        automatically each billing period until cancelled. Prices, credit allocations, and model
        access per tier are described on the pricing page and may change with notice. Payment is
        processed by third-party payment providers; we never store your card details. Refunds are
        governed by our <a href="/refund-policy" className="text-fuchsia-400 hover:text-fuchsia-300">Refund Policy</a>.
      </p>

      <SectionTitle>5. AI-Generated Content Disclaimer</SectionTitle>
      <p>
        Conversations are generated by artificial intelligence. They are fiction, not advice, and do
        not reflect the views of {siteConfig.name}. AI output may be inaccurate or unexpected. The
        characters are not conscious and no real relationship is formed. The Service is not a
        substitute for professional medical, psychological, legal, or financial counsel.
      </p>

      <SectionTitle>6. Intellectual Property</SectionTitle>
      <p>
        The Service, including character designs, artwork, and software, is owned by us or our
        licensors. You receive a personal, non-transferable license to use the Service. You retain
        rights in the messages you write; you grant us the license required to process them in order
        to operate the Service.
      </p>

      <SectionTitle>7. Termination, Liability and Changes</SectionTitle>
      <p>
        We may suspend or terminate access for violations of these terms. The Service is provided
        &quot;as is&quot; without warranties; to the maximum extent permitted by law, our liability is limited
        to the amount you paid in the twelve months before the claim. We may update these terms, and
        continued use after an update constitutes acceptance.
      </p>

      <SectionTitle>8. Contact</SectionTitle>
      <p>
        Questions about these terms: support@
        {new URL(siteConfig.url).hostname.replace(/^www\./, "")}
      </p>
    </LegalPage>
  );
}
